### ISSUE TITLE
Case-insesitive email

### ISSUE THREAD

**Issue by miko** [amborle/featmap#12]
Currently the email field is case sensitive. So you can register as John.Doe@somewhere, but receive an initation created for john.doe@somewhere (as mail servers are case insensitive).

I suggest to make email field case insensitive, possibly by making its type as citext, as mentioned on SO:
https://stackoverflow.com/questions/7005302/postgresql-how-to-make-case-insensitive-query

**Comment by amborle** [comment]
See 1f5f77ec2f2aa2c609ec160a8a675a3517c79442
