### ISSUE TITLE
Collapsing columns

### ISSUE THREAD

**Issue by miko** [amborle/featmap#14]
Would it be possible to implement collapsing of columns (for Goals), in a silimar way to the closed milestones, or to collapsing columns in other kanban tables (gitlab, wrike etc) ?

For projects with many goals (columns) the navigation becomes harder, and you do not always want to see all the goals (and their features).

**Comment by amborle** [comment]
It is possible to close goals and activities, it was added a couple of weeks ago.

![image](https://user-images.githubusercontent.com/5137189/67280374-4daa7300-f4cd-11e9-9ca7-a583d370481e.png)

**Comment by miko** [comment]
Thanks, did not notice. Would help as a workaround (unless someone forgets to reopen it). Anyways, for me close!=collapsed (collapsed is still there, its still open/relevant, but does not take that much space).

**Comment by amborle** [comment]
I don't want to introduce too many concept, that's why I am sticking with "close".
