### ISSUE TITLE
v1/account/app returns 401 Unauthorized 

### ISSUE THREAD

**Issue by mabliedana** [amborle/featmap#17]
Hi,

We have installed featmap on Ubuntu 16.04 and Windows10 OS both using Postgresql v12.

The system shows the login window. When user or password are wrong, a red message is shown, that's OK.

But if login is OK, the window remains at the login. 

Logs at the web browser are:

On page http://localhost:8081/account/login

Request URL: http://localhost:8081/v1/users/login
Request Method: POST
Status Code: 200 OK
... (jwt token is returned)

Request URL: http://localhost:8081/v1/account/app
Request Method: GET
Status Code: 401 Unauthorized

**Comment by amborle** [comment]
Can you post the config file? Remember to delete any sensitive data.

**Comment by mabliedana** [comment]
```
{  
  "appSiteURL": "http://localhost:8081/",
  "dbConnectionString": "postgresql://featmap:featmap@localhost:5432/featmap?sslmode=disable",
  "jwtSecret": "abcdeChangeMeForProduction",
  "port": "8081",
  "emailFrom" : "xxx@gmail.com",
  "smtpServer" : "smtp.gmail.com",
  "smtpPort": "587",
  "smtpUser" : "xxx@gmail.com",
  "smtpPass": "xxx",
  "environment": ""  
}
```

**Comment by amborle** [comment]
Unless you have setup https you should try
` "environment": "development"  `.


From the README.md:

**Comment by mabliedana** [comment]
Yes, sorry & Thanks
