### ISSUE TITLE
Visual indicator for long text which are only partly visible

### ISSUE THREAD

**Issue by snijhuis** [amborle/featmap#19]
Our scrum coach tipped me about this great tool for visualizing a story, thnx!

Regarding long titles: would it be possible to add a visual indicator to make clear that a title is longer than what is shown in a box. Right now some boxes seem to have strange text in them, while in reality only part of the text is shown.

**Comment by amborle** [comment]
Thanks for using Featmap! 

This is a great little feature which I will be happy to add to when I have the opportunity.

**Comment by amborle** [comment]
Done!
