### ISSUE TITLE
The UI of V2.0.0.0 is still the same as the old version

### ISSUE THREAD

**Issue by 1-2-3** [amborle/featmap#21]
I cloned the source code for V2.0.0.0, started featmap with Docker-Compose up, and found that the UI would be the same as the previous version. Why?

![featmap2 0](https://user-images.githubusercontent.com/235531/101315098-df716d00-3894-11eb-97cb-662500a53120.png)

**Comment by amborle** [comment]
There are no major UI changes in 2.0.

**Comment by 1-2-3** [comment]
Why is the UI of V2.0.0.0 self-host different from the UI screenshot in README?

**Comment by amborle** [comment]
Screenshot in readme now updated.

**Comment by 1-2-3** [comment]
I cloned the source code of V2.0.0.0 and started it using the docker-compose upD command. The UI is the same as v1.0.6 and there is no tag and other elements in the screenshot of README. Is there anything I did wrong?
![featmap2](https://user-images.githubusercontent.com/235531/101428208-3cbff980-393b-11eb-9011-323e207b669f.png)

**Comment by miko** [comment]
Try docker-compose pull. If You have amborle/featmap:latest docker image cached locally, then docker-compose up will not check for more recent version.

**Comment by amborle** [comment]
Did you run `docker-compose build`?

**Comment by 1-2-3** [comment]
> Did you run `docker-compose build`?
I run `docker-Compose Build` and the upgrade was successful. Thank you very much!
