### ISSUE TITLE
Big usability issue with "close card" button

### ISSUE THREAD

**Issue by ngirard** [amborle/featmap#28]
Hey Jens,

first of all, I wish to express my gratitude for your efforts into this great open source software !
It has proved very useful in my current project, and I'm commited to promote it within my circle.

Also, I've started looking at the source code ; no promises because I'm more of a rustacean, but I may come up with a few pull requests.

Now, the biggest problem we've experienced, hands down, is related to the "Close card" button which appears at the bottom right of the card editor.

Because of its position and the prominence of its icon, we have been constantly clicking on it by mistake whereas our intention was to simply validate the changes and close the editor.

As a result, all the cards associated to a "falsely closed" one disappear from the view, since the default behaviour is to hide the closed cards, making the mistake very difficult to detect and prevent. Unfortunately, and despite our precautions, this is what happened to us: one activity was closed by mistake, and a bunch of associated feature cards went out of our attention.

Even worse, the feature cards associated to a closed activity card still appear in the exported CSV file with an OPEN status, which is questionable in itself -- I have to think about it and might file a new issue for that. Since we use the CSV file to generate our metrics and estimates for the project, this eventually lead to an embarrassing situation where we delivered erroneous data.

So I cannot but stress on the necessity for improving the user experience related to card editing. I'd suggest, at least
- adding a second button for closing the editor next to the existing one
- changing the icon of the "close card" button

I can ask my coworker for more specific suggestions if you wish, since he's likely to be more insightful with UX-related issues.

Cheers !

**Comment by amborle** [comment]
Thank you for the kind words, I am happy you and your team are enjoying Featmap.

One thought is to simply rename the "Close card" to "Mark as Closed" or similar. That would make it pretty clear that you are actually changing the status of the card, and not just closing the window. Thoughts?

While on the topic, I am considering adding an In Progress status as well. Would this be valuable in your workflow?

**Comment by ngirard** [comment]
> One thought is to simply rename the "Close card" to "Mark as Closed" or similar. That would make it pretty clear that you are actually changing the status of the card, and not just closing the window. Thoughts?

Oh yes, changing the label would also be a welcome improvement, although I doubt it would be sufficient. The green check as an icon felt really inappropriate to us.

See for instance the icon associated with the "Close with comment" button in this very page:
![Screenshot_20210228_131804](https://user-images.githubusercontent.com/98098/109418208-667f3e80-79c7-11eb-9647-e0a691f58960.png)


> 
> While on the topic, I am considering adding an In Progress status as well. Would this be valuable in your workflow?

Yes, that would be most definitely useful !

**Comment by amborle** [comment]
Done, hope this change fixes the issue for you!

**Comment by ngirard** [comment]
Wow, thanks @amborle, I can't wait to try !

Would you mind confirming that doing
```sh
git pull
docker-compose build
```
will just rebuild Featmap and not scratch my existing Postgress database ?

**Comment by amborle** [comment]
Yes, that's what I am using. Data is kept in /data if you want to back it up, just in case.

**Comment by ngirard** [comment]
Thanks again !
I gave it a try, and confirm that your change made a big improvement !
