### ISSUE TITLE
Is it possible to host it on a custom domain?

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [amborle/featmap#44]
Hey! Thank you for a great app. I'm a bit new will all this techy stuff, but I hope you can help me.

Is it possible to host featmap on a custom domain? On something like Heroku or DO? 

It's kinda tough for me to figure it out without a step-by-step tutorial :c

**Comment by amborle** [comment]
That is indeed possible! Featmap.com is hosted on DO, for instance.

Setting up a custom domain is out of scope of this app. However, what most
people do is to run it behind a reverse proxy like Nginx or Caddy and bind
it to the domain. I am sure your can find instructions on the web.


Cheers!



Den tis 8 juni 2021 14:17Jeannétte le Flouroux ***@***.***>
skrev:
