### ISSUE TITLE
Cannot compile go-bindata

### ISSUE THREAD

**Issue by chimkan50c** [amborle/featmap#5]
Hi,

I'm new to Go and I installed it to my Mac using brew.

Then I did what the go-bindata archived git said:

    go get -u github.com/jteeuwen/go-bindata/

But then I don't know which of the go files in the directory to do 

    go install [which file??]

I cannot compile feat map without that binary.

**Comment by amborle** [comment]
Seems like generating the go-bindata files is proving a challenge to some. I have just pushed a change to add the go-bindata files to the source. With the latest source, you should be able to compile by:

`git clone https://github.com/amborle/featmap.git`
`cd featmap `
`go install`

**Comment by chimkan50c** [comment]
Thanks, I was able to compile but it leads to a second problem. (new issue)
