### ISSUE TITLE
Default Postgres credentials

### ISSUE THREAD

**Issue by chimkan50c** [amborle/featmap#7]
Hi,

Just confirming, the default Postgres:

user: featmap
database name: featmap
password: featmap

Is that right? Or I configure in the conf.json?

Thanks

**Comment by amborle** [comment]
You can use whatever database name and credentials you want, but you need
to make sure that that has all been set up correctly on the database. The
database connection string need to be in conf.json.

There are plenty of tutorials on the web on how to setup postgresql.

**Comment by chimkan50c** [comment]
I'm just putting here the syntax for connecting the PostgreSQL:

     postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
