### ISSUE TITLE
Production environment give 401 error

### ISSUE THREAD

**Issue by chimkan50c** [amborle/featmap#8]
Hi, 

I compiled, configured the database and now when I run the app, after creating the account, I cannot login. I keep seeing:

     2019/08/23 10:55:41 [Chims-MacBook-Pro.local/e5ws1k8oOj-000070] "GET http://localhost/v1/account/app HTTP/1.1" from [::1]:54069 - 401 13B in 332.253µs

The app keep rejecting my credentials and I tried resetting and even changing the values directly in the database. Then I changed the environment from production to development and it worked.

**Comment by amborle** [comment]
You are probably not serving over a https endpoint, so you need to
configure Featmap not to send secure cookies.

Try setting "environment" to "development" in conf.json, see readme.md.

**Comment by designium** [comment]
@amborle Yes, I mentioned that I changed from Production to development and it worked out. Thanks.
